[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]

[tool.poetry.dev-dependencies]
black = "^23"
flake8 = "^6"
isort = "^5"
pyright = "^1"
pytest = "^7"
pre-commit = "^3"
