[tool.poetry]
name = "cls-cps"
version = "0.1.0"
description = "A backend for synthesizing cyber-physical systems."
authors = ["Constantin Chaumet <constantin.chaumet@tu-dortmund.de>"]
readme = "README.md"
packages = [{include = "cls_cps"}]

[tool.poetry.dependencies]
python = "^3.10"
picls = {git = "https://github.com/tudo-seal/picls-python.git"}
fastapi = "^0.94.0"
uvicorn = "^0.21.0"
jsonpickle = "^3.0.1"
hypermapper = { version = "^2.2.12", optional = true }
plotly = "^5.13.1"
pydantic = "^1.10.6"
pandas = { version = "^1.5.3", optional = true }
orjson = { version = "^3.8.7", optional = true }
ujson = "^5.7.0"
pymongo = {extras = ["srv"], version = "3.13.0"}
python-decouple = "^3.8"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "main:start"
