[tool.poetry]
name = "cls-cps"
version = "0.1.0"
description = "A backend for synthesizing cyber-physical systems."
authors = ["Constantin Chaumet <constantin.chaumet@tu-dortmund.de>"]
readme = "README.md"
packages = [{include = "cls_cps"}]

[tool.poetry.dependencies]
python = "^3.10,<3.12"
picls = {git = "https://github.com/tudo-seal/picls-python.git"}
fastapi = "^0.94.0"
uvicorn = "^0.21.0"
pydantic = "^1.10.6"
pymongo = {extras = ["srv"], version = "3.13.0"}
montydb = {extras = ["bson"], version = "^2.5.2"}

[tool.poetry.group.cpython]
optional = true

[tool.poetry.group.cpython.dependencies]
ujson = "^5.7.0"
orjson = "^3.8.7"
nuitka = "^1.7.9"

[tool.poetry.group.hypermapper]
optional = true

[tool.poetry.group.hypermapper.dependencies]
hypermapper = "^2.2.12"
plotly = "^5.13.1"
pandas = "^1.5.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "main:start"
