name: Build and Publish Container

on:
  workflow_call:
  workflow_dispatch:

env:
  TEST_TAG: ghcr.io/tudo-seal/cls-cad-backend:test
  LATEST_TAG: ghcr.io/tudo-seal/cls-cad-backend:latest

jobs:
  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: applications/cls-cad-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker
        uses: docker/build-push-action@v5
        with:
          context: applications/cls-cad-backend
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: ${{ env.TEST_TAG }}
        if: github.event_name == 'pull_request'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: applications/cls-cad-backend
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ env.LATEST_TAG }}
          provenance: false
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
