name: Run Tests
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    defaults:
      run:
        working-directory: applications/cls-cad-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --with docker --no-interaction
      - name: Install dependencies
        run: touch cls_cad_backend/database/container
      - name: Test with pytest
        run: poetry run pytest --cov=. --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
          working-directory: applications/cls-cad-backend
